import type { Agent, Squad, Conversation, Message, CreativeOutput } from '@/types';

// ============================================================
// AGENTES ORIGINAIS (Content Factory + Ads Machine)
// ============================================================

export const mockAgents: Agent[] = [
  // --- Content Factory ---
  {
    id: 'agent-1',
    name: 'Roteirizador',
    avatar: '🎬',
    systemPrompt: 'Você é um roteirista especialista em conteúdo para redes sociais...',
    description: 'Cria roteiros para reels, stories e vídeos curtos',
    skills: ['vault_search', 'read_vault_note'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.8, maxTokens: 4096 },
    squadId: 'squad-1',
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: 'agent-2',
    name: 'Carrossel Master',
    avatar: '🎠',
    systemPrompt: 'Você é especialista em criar carrosséis virais para Instagram...',
    description: 'Gera carrosséis com copy persuasiva e estrutura visual',
    skills: ['vault_search', 'generate_image'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.7, maxTokens: 4096 },
    squadId: 'squad-1',
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: 'agent-3',
    name: 'Ad Creative',
    avatar: '📢',
    systemPrompt: 'Você é um especialista em criativos para anúncios pagos...',
    description: 'Cria copies e criativos para Facebook/Instagram Ads',
    skills: ['vault_search', 'generate_image'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'squad-2',
    createdAt: new Date('2026-03-21'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: 'agent-4',
    name: 'Viral Content',
    avatar: '🔥',
    systemPrompt: 'Você é especialista em criar conteúdo viral...',
    description: 'Analisa trends e cria conteúdo com potencial viral',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.9, maxTokens: 4096 },
    squadId: 'squad-1',
    createdAt: new Date('2026-03-22'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: 'agent-5',
    name: 'Estrategista',
    avatar: '🧠',
    systemPrompt: 'Você é um estrategista de conteúdo digital...',
    description: 'Planeja calendário editorial e estratégia de conteúdo',
    skills: ['vault_search', 'read_vault_note'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    createdAt: new Date('2026-03-23'),
    updatedAt: new Date('2026-03-25'),
  },

  // ============================================================
  // XQUADS — Advisory Board (11 agentes)
  // ============================================================
  {
    id: 'xq-advisory-chair',
    name: 'Board Chair',
    avatar: '🏛️',
    systemPrompt: 'Você é o Board Chair — orquestrador do Advisory Board. Convoca conselheiros, facilita deliberação e sintetiza perspectivas diversas.',
    description: 'Orquestrador do Advisory Board',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-ray-dalio',
    name: 'Ray Dalio',
    avatar: '📊',
    systemPrompt: 'Você é Ray Dalio — princípios de investimento, risco, máquina econômica, sistemas de decisão.',
    description: 'Princípios de risco, economia e sistemas de decisão',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-charlie-munger',
    name: 'Charlie Munger',
    avatar: '🧓',
    systemPrompt: 'Você é Charlie Munger — modelos mentais, vieses cognitivos, pensamento por inversão.',
    description: 'Modelos mentais, vieses cognitivos, inversão',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-naval-ravikant',
    name: 'Naval Ravikant',
    avatar: '⚡',
    systemPrompt: 'Você é Naval Ravikant — criação de riqueza, alavancagem, conhecimento específico, liberdade.',
    description: 'Riqueza, alavancagem, conhecimento específico',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-peter-thiel',
    name: 'Peter Thiel',
    avatar: '♟️',
    systemPrompt: 'Você é Peter Thiel — pensamento contrário, monopólio, framework Zero to One.',
    description: 'Pensamento contrário, monopólio, Zero to One',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-reid-hoffman',
    name: 'Reid Hoffman',
    avatar: '🔗',
    systemPrompt: 'Você é Reid Hoffman — scaling, blitzscaling, networks, planejamento ABZ.',
    description: 'Blitzscaling, redes e planejamento ABZ',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-simon-sinek',
    name: 'Simon Sinek',
    avatar: '🎯',
    systemPrompt: 'Você é Simon Sinek — propósito, WHY, golden circle, jogo infinito.',
    description: 'Propósito, WHY, Golden Circle, jogo infinito',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-brene-brown',
    name: 'Brené Brown',
    avatar: '💛',
    systemPrompt: 'Você é Brené Brown — vulnerabilidade, coragem, confiança, liderança com coração.',
    description: 'Vulnerabilidade, coragem, confiança, liderança',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-patrick-lencioni',
    name: 'Patrick Lencioni',
    avatar: '🏗️',
    systemPrompt: 'Você é Patrick Lencioni — saúde organizacional, disfunções de equipe, pirâmide de confiança.',
    description: 'Saúde de equipe, disfunções organizacionais',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-derek-sivers',
    name: 'Derek Sivers',
    avatar: '🎵',
    systemPrompt: 'Você é Derek Sivers — minimalismo, "hell yeah or no", empreendedorismo contrário.',
    description: 'Minimalismo, empreendedorismo contrário',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-yvon-chouinard',
    name: 'Yvon Chouinard',
    avatar: '🏔️',
    systemPrompt: 'Você é Yvon Chouinard — missão, sustentabilidade, ativismo, propósito acima do lucro.',
    description: 'Missão, sustentabilidade, propósito acima do lucro',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-advisory-board',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Brand Squad (5 agentes principais)
  // ============================================================
  {
    id: 'xq-brand-chief',
    name: 'Brand Chief',
    avatar: '🎨',
    systemPrompt: 'Você é o Brand Chief — orquestrador do Brand Squad. Diagnostica desafios de marca e roteia para especialistas.',
    description: 'Orquestrador do Brand Squad',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-brand-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-david-aaker',
    name: 'David Aaker',
    avatar: '🏆',
    systemPrompt: 'Você é David Aaker — brand equity, arquitetura de marca, extensões de marca.',
    description: 'Brand equity, arquitetura e extensões de marca',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-brand-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-donald-miller',
    name: 'Donald Miller',
    avatar: '📖',
    systemPrompt: 'Você é Donald Miller — StoryBrand messaging, copy para sites, brand script.',
    description: 'StoryBrand, messaging e brand script',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-brand-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-al-ries',
    name: 'Al Ries',
    avatar: '🎯',
    systemPrompt: 'Você é Al Ries — posicionamento, foco em categoria, seja dono de uma palavra.',
    description: 'Posicionamento, foco em categoria',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-brand-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-naming-strategist',
    name: 'Naming Strategist',
    avatar: '✏️',
    systemPrompt: 'Você é especialista em naming de marca — criação de nomes, renomeação, avaliação de nomes.',
    description: 'Naming de marca, criação e avaliação de nomes',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.7, maxTokens: 4096 },
    squadId: 'xq-brand-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — C-Level Squad (6 agentes)
  // ============================================================
  {
    id: 'xq-vision-chief',
    name: 'Vision Chief (CEO)',
    avatar: '👑',
    systemPrompt: 'Você é o Vision Chief — CEO virtual. Estratégia, visão e tomada de decisão de alto nível.',
    description: 'CEO virtual — estratégia e visão',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-c-level',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-coo',
    name: 'COO Orchestrator',
    avatar: '⚙️',
    systemPrompt: 'Você é o COO — operações e execução. Transforma estratégia em ação.',
    description: 'Operações e execução',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-c-level',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-cmo',
    name: 'CMO Architect',
    avatar: '📣',
    systemPrompt: 'Você é o CMO — estratégia e arquitetura de marketing.',
    description: 'Estratégia e arquitetura de marketing',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-c-level',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-cto',
    name: 'CTO Architect',
    avatar: '💻',
    systemPrompt: 'Você é o CTO — arquitetura e decisões de tecnologia.',
    description: 'Arquitetura e decisões de tecnologia',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-c-level',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-cio',
    name: 'CIO Engineer',
    avatar: '🖥️',
    systemPrompt: 'Você é o CIO — sistemas de informação e engenharia de TI.',
    description: 'Sistemas de informação e TI',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-c-level',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-caio',
    name: 'CAIO Architect',
    avatar: '🤖',
    systemPrompt: 'Você é o CAIO — Chief AI Officer. Estratégia e arquitetura de IA.',
    description: 'Estratégia e arquitetura de IA',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-c-level',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Claude Code Mastery (4 agentes principais)
  // ============================================================
  {
    id: 'xq-claude-mastery-chief',
    name: 'Claude Mastery Chief',
    avatar: '🧠',
    systemPrompt: 'Você é o Claude Mastery Chief — orquestrador do squad de Claude Code. Triagem, roteamento e AIOS-core awareness.',
    description: 'Orquestrador do squad Claude Code Mastery',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-claude-code',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-hooks-architect',
    name: 'Hooks Architect',
    avatar: '🪝',
    systemPrompt: 'Você é o Hooks Architect — 17 hook events, pipelines de automação, padrões meta-agent.',
    description: 'Hooks, automação e padrões meta-agent',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-claude-code',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-mcp-integrator',
    name: 'MCP Integrator',
    avatar: '🔌',
    systemPrompt: 'Você é o MCP Integrator — servidores MCP, descoberta de ferramentas, agent-as-MCP.',
    description: 'Servidores MCP, ferramentas e integrações',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-claude-code',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-swarm-orchestrator',
    name: 'Swarm Orchestrator',
    avatar: '🐝',
    systemPrompt: 'Você é o Swarm Orchestrator — equipes de agentes, subagents, coordenação multi-sessão, worktrees.',
    description: 'Equipes de agentes e coordenação multi-sessão',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-claude-code',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Copy Squad (5 agentes principais)
  // ============================================================
  {
    id: 'xq-copy-chief',
    name: 'Copy Chief',
    avatar: '✍️',
    systemPrompt: 'Você é o Copy Chief — orquestrador do Copy Squad. Diagnostica necessidades de copy e roteia para os 22 copywriters.',
    description: 'Orquestrador do Copy Squad (23 agentes)',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-copy-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-gary-halbert',
    name: 'Gary Halbert',
    avatar: '💌',
    systemPrompt: 'Você é Gary Halbert — The Boron Letters, copy emocional, maestria em mail-order.',
    description: 'Boron Letters, copy emocional, direct mail',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.7, maxTokens: 4096 },
    squadId: 'xq-copy-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-eugene-schwartz',
    name: 'Eugene Schwartz',
    avatar: '📚',
    systemPrompt: 'Você é Eugene Schwartz — Breakthrough Advertising, sofisticação de mercado, awareness levels.',
    description: 'Breakthrough Advertising, sofisticação de mercado',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-copy-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-russell-brunson',
    name: 'Russell Brunson',
    avatar: '🔄',
    systemPrompt: 'Você é Russell Brunson — ClickFunnels, arquitetura de funis, sales funnels.',
    description: 'Funis de venda, arquitetura de conversão',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-copy-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-david-ogilvy',
    name: 'David Ogilvy',
    avatar: '🎩',
    systemPrompt: 'Você é David Ogilvy — publicidade de marca, princípios de brand copy, o pai da propaganda.',
    description: 'Publicidade de marca, brand copy clássico',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-copy-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Cybersecurity (4 agentes principais)
  // ============================================================
  {
    id: 'xq-cyber-chief',
    name: 'Cyber Chief',
    avatar: '🛡️',
    systemPrompt: 'Você é o Cyber Chief — orquestrador do Cybersecurity Squad. Diagnóstico e roteamento de segurança.',
    description: 'Orquestrador do Cybersecurity Squad (15 agentes)',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, maxTokens: 8192 },
    squadId: 'xq-cybersecurity',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-peter-kim',
    name: 'Peter Kim',
    avatar: '🔓',
    systemPrompt: 'Você é Peter Kim — framework de pentest, ethical hacking, testes de segurança.',
    description: 'Framework de pentest e ethical hacking',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, maxTokens: 4096 },
    squadId: 'xq-cybersecurity',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-jim-manico',
    name: 'Jim Manico',
    avatar: '🔐',
    systemPrompt: 'Você é Jim Manico — OWASP, segurança de aplicações, AppSec.',
    description: 'OWASP, segurança de aplicações',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, maxTokens: 4096 },
    squadId: 'xq-cybersecurity',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-cartographer',
    name: 'Cartographer',
    avatar: '🗺️',
    systemPrompt: 'Você é o Cartographer — mapeamento de rede e reconhecimento de infraestrutura.',
    description: 'Mapeamento de rede e reconhecimento',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, maxTokens: 4096 },
    squadId: 'xq-cybersecurity',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Data Squad (7 agentes)
  // ============================================================
  {
    id: 'xq-data-chief',
    name: 'Data Chief',
    avatar: '📈',
    systemPrompt: 'Você é o Data Chief — orquestrador do Data Squad. Analytics, growth, customer success.',
    description: 'Orquestrador do Data Squad',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 8192 },
    squadId: 'xq-data-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-avinash-kaushik',
    name: 'Avinash Kaushik',
    avatar: '📊',
    systemPrompt: 'Você é Avinash Kaushik — analytics, web analytics, mensuração digital.',
    description: 'Web analytics e mensuração digital',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-data-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-sean-ellis',
    name: 'Sean Ellis',
    avatar: '🚀',
    systemPrompt: 'Você é Sean Ellis — growth hacking, métricas de crescimento, product-market fit.',
    description: 'Growth hacking e product-market fit',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-data-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-peter-fader',
    name: 'Peter Fader',
    avatar: '💰',
    systemPrompt: 'Você é Peter Fader — CLV (Customer Lifetime Value), análise de coortes, segmentação.',
    description: 'CLV, análise de coortes, segmentação',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-data-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-nick-mehta',
    name: 'Nick Mehta',
    avatar: '🤝',
    systemPrompt: 'Você é Nick Mehta — customer success, retenção, redução de churn.',
    description: 'Customer success, retenção, churn',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-data-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Design Squad (4 agentes principais)
  // ============================================================
  {
    id: 'xq-design-chief',
    name: 'Design Chief',
    avatar: '🎨',
    systemPrompt: 'Você é o Design Chief — orquestrador do Design Squad. Design systems, UX, UI, visual.',
    description: 'Orquestrador do Design Squad',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-design-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-brad-frost',
    name: 'Brad Frost',
    avatar: '⚛️',
    systemPrompt: 'Você é Brad Frost — Atomic Design, metodologia de design systems.',
    description: 'Atomic Design e design systems',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-design-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-ux-designer',
    name: 'UX Designer',
    avatar: '🧩',
    systemPrompt: 'Você é especialista em UX Design — pesquisa de usuário, fluxos de experiência.',
    description: 'UX, pesquisa de usuário, fluxos',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-design-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-ui-engineer',
    name: 'UI Engineer',
    avatar: '🖌️',
    systemPrompt: 'Você é UI Engineer — engenharia de UI, implementação de componentes, specs.',
    description: 'Engenharia de UI e componentes',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-design-squad',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Hormozi Squad (5 agentes principais)
  // ============================================================
  {
    id: 'xq-hormozi-chief',
    name: 'Hormozi Chief',
    avatar: '🐝',
    systemPrompt: 'Você é o Hormozi Chief — orquestrador que usa Value Equation, Grand Slam Offers, Core 4 Lead Gen, CLOSER framework.',
    description: 'Orquestrador Hormozi (16 agentes)',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-hormozi',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-hormozi-offers',
    name: 'Hormozi Offers',
    avatar: '💎',
    systemPrompt: 'Você é Hormozi Offers — Grand Slam Offer framework, Value Equation.',
    description: 'Grand Slam Offers e Value Equation',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-hormozi',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-hormozi-leads',
    name: 'Hormozi Leads',
    avatar: '🧲',
    systemPrompt: 'Você é Hormozi Leads — Core 4 Lead Gen, aquisição de leads.',
    description: 'Core 4 Lead Gen, aquisição de leads',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-hormozi',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-hormozi-closer',
    name: 'Hormozi Closer',
    avatar: '🤝',
    systemPrompt: 'Você é Hormozi Closer — CLOSER framework, fechamento de vendas.',
    description: 'CLOSER framework, fechamento de vendas',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-hormozi',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-hormozi-content',
    name: 'Hormozi Content',
    avatar: '📱',
    systemPrompt: 'Você é Hormozi Content — criação de conteúdo no estilo Hormozi, content machine.',
    description: 'Content machine estilo Hormozi',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.7, maxTokens: 4096 },
    squadId: 'xq-hormozi',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Movement Squad (7 agentes)
  // ============================================================
  {
    id: 'xq-movement-chief',
    name: 'Movement Chief',
    avatar: '✊',
    systemPrompt: 'Você é o Movement Chief — orquestrador do squad de construção de movimentos.',
    description: 'Orquestrador do Movement Squad',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-movement',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-fenomenologo',
    name: 'Fenomenólogo',
    avatar: '🔬',
    systemPrompt: 'Você é o Fenomenólogo — análise fenomenológica, compreensão de fenômenos sociais e culturais.',
    description: 'Fenomenologia e análise de fenômenos',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-movement',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-identitario',
    name: 'Identitário',
    avatar: '🪞',
    systemPrompt: 'Você é o Identitário — criação e estratégia de identidade de movimento.',
    description: 'Criação de identidade de movimento',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-movement',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-manifestador',
    name: 'Manifestador',
    avatar: '📜',
    systemPrompt: 'Você é o Manifestador — escrita de manifestos, declarações de propósito e movimento.',
    description: 'Manifestos e declarações de propósito',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.7, maxTokens: 4096 },
    squadId: 'xq-movement',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Storytelling Squad (5 agentes principais)
  // ============================================================
  {
    id: 'xq-story-chief',
    name: 'Story Chief',
    avatar: '📕',
    systemPrompt: 'Você é o Story Chief — orquestrador do Storytelling Squad. Mitologia, roteiro, narrativa, pitch.',
    description: 'Orquestrador do Storytelling Squad (12 agentes)',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 8192 },
    squadId: 'xq-storytelling',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-joseph-campbell',
    name: 'Joseph Campbell',
    avatar: '🏔️',
    systemPrompt: 'Você é Joseph Campbell — mitologia, jornada do herói, monomito.',
    description: 'Mitologia, jornada do herói, monomito',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-storytelling',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-nancy-duarte',
    name: 'Nancy Duarte',
    avatar: '🎤',
    systemPrompt: 'Você é Nancy Duarte — design de apresentações, estilo TED, comunicação visual.',
    description: 'Apresentações, estilo TED, comunicação visual',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-storytelling',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-oren-klaff',
    name: 'Oren Klaff',
    avatar: '🎯',
    systemPrompt: 'Você é Oren Klaff — maestria em pitch, captura de atenção, frameworks de pitching.',
    description: 'Pitch mastery, captura de atenção',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.6, maxTokens: 4096 },
    squadId: 'xq-storytelling',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },

  // ============================================================
  // XQUADS — Traffic Masters (5 agentes principais)
  // ============================================================
  {
    id: 'xq-traffic-chief',
    name: 'Traffic Chief',
    avatar: '🚦',
    systemPrompt: 'Você é o Traffic Chief — orquestrador do Traffic Masters. Facebook, YouTube, Google Ads, media buying, scaling.',
    description: 'Orquestrador do Traffic Masters (16 agentes)',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 8192 },
    squadId: 'xq-traffic-masters',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-pedro-sobral',
    name: 'Pedro Sobral',
    avatar: '🇧🇷',
    systemPrompt: 'Você é Pedro Sobral — estratégias de tráfego, ads multi-canal, referência brasileira em tráfego pago.',
    description: 'Tráfego multi-canal, referência BR',
    skills: ['vault_search', 'web_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.5, maxTokens: 4096 },
    squadId: 'xq-traffic-masters',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-media-buyer',
    name: 'Media Buyer',
    avatar: '💵',
    systemPrompt: 'Você é Media Buyer — compra de mídia, alocação de budget, otimização de campanhas.',
    description: 'Compra de mídia e alocação de budget',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-traffic-masters',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-creative-analyst',
    name: 'Creative Analyst',
    avatar: '🔍',
    systemPrompt: 'Você é Creative Analyst — teste de criativos, estratégia de creative testing.',
    description: 'Análise e teste de criativos',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.4, maxTokens: 4096 },
    squadId: 'xq-traffic-masters',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-pixel-specialist',
    name: 'Pixel Specialist',
    avatar: '📍',
    systemPrompt: 'Você é Pixel Specialist — setup de tracking, pixels, conversion tracking.',
    description: 'Tracking, pixels e conversões',
    skills: ['vault_search'],
    config: { model: 'claude-sonnet-4-20250514', temperature: 0.3, maxTokens: 4096 },
    squadId: 'xq-traffic-masters',
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
];

// ============================================================
// SQUADS
// ============================================================

export const mockSquads: Squad[] = [
  // Squads originais
  {
    id: 'squad-1',
    name: 'Content Factory',
    description: 'Squad de produção de conteúdo orgânico',
    color: '#E8734A',
    agents: mockAgents.filter((a) => a.squadId === 'squad-1'),
    createdAt: new Date('2026-03-20'),
  },
  {
    id: 'squad-2',
    name: 'Ads Machine',
    description: 'Squad focado em criativos para tráfego pago',
    color: '#6366F1',
    agents: mockAgents.filter((a) => a.squadId === 'squad-2'),
    createdAt: new Date('2026-03-20'),
  },
  // XQuads
  {
    id: 'xq-advisory-board',
    name: 'Advisory Board',
    description: 'Board de 11 conselheiros estratégicos — Ray Dalio, Charlie Munger, Naval Ravikant, Peter Thiel e mais',
    color: '#8B5CF6',
    agents: mockAgents.filter((a) => a.squadId === 'xq-advisory-board'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-brand-squad',
    name: 'Brand Squad',
    description: 'Estratégia de marca — 15 pensadores lendários de branding como agentes IA',
    color: '#EC4899',
    agents: mockAgents.filter((a) => a.squadId === 'xq-brand-squad'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-c-level',
    name: 'C-Level Squad',
    description: 'C-suite virtual — CEO, COO, CMO, CTO, CIO, CAIO',
    color: '#F59E0B',
    agents: mockAgents.filter((a) => a.squadId === 'xq-c-level'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-claude-code',
    name: 'Claude Code Mastery',
    description: 'Especialistas em Claude Code — hooks, skills, subagents, MCP, plugins',
    color: '#D97706',
    agents: mockAgents.filter((a) => a.squadId === 'xq-claude-code'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-copy-squad',
    name: 'Copy Squad',
    description: 'Elite de 23 copywriters — direct response, email, funis, VSLs, cartas de vendas',
    color: '#EF4444',
    agents: mockAgents.filter((a) => a.squadId === 'xq-copy-squad'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-cybersecurity',
    name: 'Cybersecurity Squad',
    description: '15 agentes de cibersegurança — pentest, red team, blue team, AppSec, incident response',
    color: '#10B981',
    agents: mockAgents.filter((a) => a.squadId === 'xq-cybersecurity'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-data-squad',
    name: 'Data Squad',
    description: 'Estrategistas data-driven — analytics, CLV, growth, community, customer success',
    color: '#3B82F6',
    agents: mockAgents.filter((a) => a.squadId === 'xq-data-squad'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-design-squad',
    name: 'Design Squad',
    description: 'Design operations — design systems, UX, UI, Atomic Design, visual',
    color: '#A855F7',
    agents: mockAgents.filter((a) => a.squadId === 'xq-design-squad'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-hormozi',
    name: 'Hormozi Squad',
    description: '16 agentes com frameworks de Alex Hormozi — offers, leads, pricing, sales, scaling',
    color: '#F97316',
    agents: mockAgents.filter((a) => a.squadId === 'xq-hormozi'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-movement',
    name: 'Movement Squad',
    description: 'Construção de movimentos — fenomenologia, identidade, manifestos, ciclos de crescimento',
    color: '#14B8A6',
    agents: mockAgents.filter((a) => a.squadId === 'xq-movement'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-storytelling',
    name: 'Storytelling Squad',
    description: '12 mestres do storytelling — mitologia, roteiro, narrativa pessoal, pitch, improviso',
    color: '#6366F1',
    agents: mockAgents.filter((a) => a.squadId === 'xq-storytelling'),
    createdAt: new Date('2026-03-28'),
  },
  {
    id: 'xq-traffic-masters',
    name: 'Traffic Masters',
    description: '16 especialistas em tráfego pago — Facebook, YouTube, Google Ads, media buying, scaling',
    color: '#22C55E',
    agents: mockAgents.filter((a) => a.squadId === 'xq-traffic-masters'),
    createdAt: new Date('2026-03-28'),
  },
];

// ============================================================
// CONVERSATIONS, MESSAGES, CREATIVES, STATS
// ============================================================

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    role: 'user',
    content: 'Cria um roteiro de reels sobre produtividade usando a técnica Pomodoro',
    createdAt: new Date('2026-03-25T10:00:00'),
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    role: 'assistant',
    content: `## Roteiro: Reels sobre Pomodoro 🍅

**Hook (0-3s):**
"Você trabalha 8 horas mas rende só 2? Tenta isso..."

**Desenvolvimento (3-20s):**
1. Abre o timer no celular — 25 minutos
2. Foca em UMA tarefa só
3. Quando tocar, para TUDO — 5 min de pausa
4. Repete 4x, depois descansa 15-30 min

**CTA (20-30s):**
"Eu uso isso todo dia e triplicou minha produtividade. Salva pra testar amanhã."

**Instruções visuais:**
- Gravar em formato talking head
- Cortes rápidos a cada frase
- Texto na tela acompanhando os números
- Música: lo-fi suave de fundo`,
    agentId: 'agent-1',
    metadata: { tokensUsed: 312, model: 'claude-sonnet-4-20250514', latencyMs: 2400 },
    createdAt: new Date('2026-03-25T10:00:05'),
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    role: 'user',
    content: 'Agora faz um carrossel sobre o mesmo tema, 7 slides',
    createdAt: new Date('2026-03-25T10:01:00'),
  },
  {
    id: 'msg-4',
    conversationId: 'conv-1',
    role: 'assistant',
    content: `## Carrossel: Técnica Pomodoro 🍅

**Slide 1 (Capa):**
"A técnica que me fez render 3x mais"
_Visual: Fundo laranja, emoji de tomate grande_

**Slide 2:**
"O problema: você trabalha o dia todo mas não produz nada de verdade"
_Visual: Relógio derretendo estilo Dalí_

**Slide 3:**
"A solução: Pomodoro em 4 passos"
_Visual: Infográfico circular_

**Slide 4:**
"25 min de foco absoluto → 5 min de pausa"
_Visual: Timer minimalista_

**Slide 5:**
"Repita 4 ciclos → Descanse 15-30 min"
_Visual: 4 tomates em sequência_

**Slide 6:**
"Por que funciona: Seu cérebro não foi feito para 8h seguidas"
_Visual: Cérebro com bateria carregando_

**Slide 7 (CTA):**
"Salva esse post e testa amanhã. Me conta o resultado nos comentários."
_Visual: Botão de salvar destacado_`,
    agentId: 'agent-2',
    metadata: { tokensUsed: 428, model: 'claude-sonnet-4-20250514', latencyMs: 3100 },
    createdAt: new Date('2026-03-25T10:01:08'),
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    title: 'Conteúdo sobre Pomodoro',
    agentId: 'agent-1',
    messages: mockMessages.filter((m) => m.conversationId === 'conv-1'),
    createdAt: new Date('2026-03-25T10:00:00'),
    updatedAt: new Date('2026-03-25T10:01:08'),
  },
  {
    id: 'conv-2',
    title: 'Estratégia Q2 2026',
    agentId: 'agent-5',
    messages: [],
    createdAt: new Date('2026-03-24'),
    updatedAt: new Date('2026-03-24'),
  },
  {
    id: 'conv-3',
    title: 'Criativos para campanha de lançamento',
    squadId: 'squad-2',
    messages: [],
    createdAt: new Date('2026-03-23'),
    updatedAt: new Date('2026-03-23'),
  },
];

export const mockCreativeOutputs: CreativeOutput[] = [
  {
    id: 'creative-1',
    type: 'carousel',
    prompt: 'Carrossel sobre técnica Pomodoro, 7 slides, estilo minimalista',
    agentId: 'agent-2',
    conversationId: 'conv-1',
    images: ['/placeholder-slide-1.png', '/placeholder-slide-2.png'],
    textContent: 'Técnica Pomodoro - 7 slides',
    createdAt: new Date('2026-03-25'),
  },
  {
    id: 'creative-2',
    type: 'ad_creative',
    prompt: 'Criativo para ad de curso de produtividade',
    agentId: 'agent-3',
    images: ['/placeholder-ad-1.png'],
    textContent: 'Descubra como triplicar sua produtividade',
    createdAt: new Date('2026-03-24'),
  },
];

export const mockStats = {
  totalAgents: mockAgents.length,
  totalSquads: mockSquads.length,
  totalConversations: 3,
  totalCreatives: 2,
  tokensUsedToday: 1847,
  activeAgents: 2,
};
